name: Check YouTube Channel Updates

on:
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

jobs:
  check-updates:
    runs-on: ubuntu-latest
    
    # ------ 需add以下兩行 ------
    # 否則出 403 Forbidden, GitHub Actions預設只授予"read" repo權限。 但git-auto-commit-action 這工具需"寫入"權限，
    # 才能將新的 status.json 推送回來。 below is 403 Forbidden錯誤:
    # remote: Permission to xxx/youtube-new-vid-rss-checker.git denied to github-actions[bot].
    # fatal: unable to access 'https://github.com/xxx/youtube-new-vid-rss-checker/': The requested URL returned error: 403
    permissions:
      contents: write
    # ---------------------------
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser pytz

      - name: Run YouTube check script
        run: python check_youtube.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Automated check: Update YouTube status'
          file_pattern: 'status.json last_check.json'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_author: 'github-actions[bot] <github-actions[bot]@users.noreply.github.com>'
